In [2]:
import numpy as np

In [6]:
a=np.random.randint(30,99,(7,8))
a

array([[94, 72, 74, 32, 49, 44, 89, 33],
       [67, 89, 98, 69, 68, 72, 50, 65],
       [69, 42, 86, 52, 82, 89, 97, 83],
       [32, 40, 84, 73, 97, 89, 67, 76],
       [70, 63, 50, 62, 68, 43, 85, 42],
       [60, 60, 64, 96, 34, 91, 39, 77],
       [33, 55, 74, 86, 55, 35, 35, 42]])

In [10]:
np.random.randint.seed(a)
a

AttributeError: 'builtin_function_or_method' object has no attribute 'seed'

In [12]:
a.ndim

2

In [16]:
b=np.random.randint(20,80,(8,9))
b

array([[29, 67, 78, 56, 65, 73, 34, 49, 26],
       [55, 60, 53, 30, 75, 71, 35, 79, 39],
       [27, 75, 78, 56, 72, 34, 27, 68, 56],
       [74, 41, 28, 64, 68, 44, 48, 31, 76],
       [45, 41, 66, 60, 32, 23, 33, 48, 71],
       [22, 27, 38, 29, 27, 69, 67, 73, 37],
       [59, 25, 43, 66, 20, 36, 50, 31, 37],
       [22, 29, 45, 62, 52, 43, 63, 59, 25]])

In [18]:
b.shape

(8, 9)

In [20]:
b.ndim

2

In [22]:
b[7,0]

22

In [24]:
#slicing array array[rs:re:rstep,cs:ce:cstep]
b[2:6:1,::]

array([[27, 75, 78, 56, 72, 34, 27, 68, 56],
       [74, 41, 28, 64, 68, 44, 48, 31, 76],
       [45, 41, 66, 60, 32, 23, 33, 48, 71],
       [22, 27, 38, 29, 27, 69, 67, 73, 37]])

In [26]:
b[2:6:1,1:7]

array([[75, 78, 56, 72, 34, 27],
       [41, 28, 64, 68, 44, 48],
       [41, 66, 60, 32, 23, 33],
       [27, 38, 29, 27, 69, 67]])

In [28]:
b[2:6:1,1:7:2]

array([[75, 56, 34],
       [41, 64, 44],
       [41, 60, 23],
       [27, 29, 69]])

In [30]:
b[1:5,1:7]

array([[60, 53, 30, 75, 71, 35],
       [75, 78, 56, 72, 34, 27],
       [41, 28, 64, 68, 44, 48],
       [41, 66, 60, 32, 23, 33]])